version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 20
    target-branch: master
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 20
    target-branch: master
