site_name: ProxyGrab
repo_url: https://github.com/Divkix/ProxyGrab/
site_description: ProxyGrab is a small package to get proxies from multiple services easily, by either using API or by scrapping them from various websites!
edit_uri: tree/master/docs/
site_author: Divkix
use_directory_urls: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Command Line: console.md
  - API: api.md
  - FAQ: faq.md
theme:
  name: material
  custom_dir: docs/overrides
  logo: img/circle-icon.png
  favicon: img/name.png
  palette:
    - scheme: preference
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Divkix/ProxyGrab
      name: ProxyGrab on Github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
