site_name: ProxyGrab
repo_url: https://github.com/SkuzzyxD/ProxyGrab/
site_description: ProxyGrab is a small package to get proxies from multiple servers easily, by either using API or by scrapping them.
edit_uri: tree/master/docs/
site_author: Skuzzy xD
use_directory_urls: true
nav:
    - Home: index.md
    - Installation: installation.md
    - Command Line: console.md
    - Script: script.md
    - ProxyScrape Premium: proxyscrape_premium.md
    - FAQ: faq.md
theme:
  name: material
  logo: img/circle-icon.png
  favicon: img/name.png
  palette:
    scheme: preference
    primary: teal
    accent: amber
  icon:
    repo: fontawesome/brands/github-alt
plugins:
  - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SkuzzyxD/ProxyGrab
      name: ProxyGrab on Github
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/SkuzzyxD
      name: Official YouTube Channel
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/Skuzzers
      name: Skuzzers Telegram Channel
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
