name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  build-and-test:
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    uses: divkix/reusable-workflows/.github/workflows/build-and-test-python-package.yml@main
    with:
      custom_commands: |-
        proxygrab --help
        python test_script.py
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}

  automerge-dependabot-pr:
    name: Automerge Dependabot PRs
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs:
      - pre-commit
      - build-and-test
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
