name: CI (pip)

on:
  push:
    branches:
      - master
    paths:
      - "proxygrab/*"
      - "pyproject.toml"
      - ".github/workflows/continuous-integration-pip.yml"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: "Run Reason"
        required: false

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies & Configuring
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install --upgrade poetry
          poetry config virtualenvs.create false
          poetry install

      - name: ProxyGrab CLI
        run: |
          proxygrab --help
          proxygrab -h

      - name: Proxygrab Test Module
        run: python test_script.py

  push-to-pypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
