name: Dependabot auto merge
on:
 pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-comment: Dependabot PR Auto Merge
