name: Build and Push Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: "Update Reason"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install --upgrade poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Build Docs
        run: |
          mkdocs build

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./site"
